pub const ERROR_PLAYER_ALREADY_EXIST: u32 = 1;
pub const ERROR_PLAYER_NOT_EXIST: u32 = 2;
pub const ERROR_NOT_SELECTED_PLAYER: u32 = 3;
pub const SELECTED_PLAYER_NOT_EXIST: u32 = 4;
pub const ROUND_NO_REWARD: u32 = 5;
pub const ROUND_NOT_FINISHED: u32 = 6;
pub const PLAYER_NOT_ENOUGH_INVENTORY: u32 = 7;
pub const PLAYER_NOT_ENOUGH_BALANCE: u32 = 8;

